version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
      - image: redis:4.0.1-alpine
        name: redis

    steps:
      - checkout

      - run:
          name: install python-dev
          command: sudo apt install -y python3-dev

      - restore_cache:
          name: Restore virtualenvs from previous builds
          key: virtualenvs-dependencies-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}

      - run:
          name: Install Poetry and project's dependencies
          command: |
            export TERM=xterm-256color
            export COLUMNS=150
            curl -sSL https://install.python-poetry.org | python3 -
            poetry install --with dev

      - save_cache:
          name: Save virtualenvs cache for future builds
          key: virtualenvs-dependencies-cache-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs

      - run:
          name: run tests
          command: |
            poetry run pytest
