"""initial

Revision ID: 266f2bb4c870
Revises: 
Create Date: 2022-01-04 14:02:01.378899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266f2bb4c870'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_query_received_at'), 'broadcast_query', ['received_at'], unique=False)
    op.create_table('pigeonhole_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('message', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pigeonhole_message_address'), 'pigeonhole_message', ['address'], unique=False)
    op.create_index(op.f('ix_pigeonhole_message_received_at'), 'pigeonhole_message', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pigeonhole_message_received_at'), table_name='pigeonhole_message')
    op.drop_index(op.f('ix_pigeonhole_message_address'), table_name='pigeonhole_message')
    op.drop_table('pigeonhole_message')
    op.drop_index(op.f('ix_broadcast_query_received_at'), table_name='broadcast_query')
    op.drop_table('broadcast_query')
    # ### end Alembic commands ###
